version: '3.8'

services:
  rag_backend:
    build: .
    container_name: rag_backend
    depends_on:
      - db
    ports:
      - "${APP_PORT}:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
    volumes:
      - "${HOME_DIR}/rag_backend/.env:/app/.env"
    networks:
      - rag_net
    restart: unless-stopped

  db:
    image: ankane/pgvector:latest
    container_name: pgvector
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "${HOME_DIR}/postgresql/data:/var/lib/postgresql/data"
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - rag_net
    restart: unless-stopped

networks:
  rag_net:
    driver: bridge